export interface CitySeed { nameRu: string; nameBe: string; region: 'Минская' | 'Брестская' | 'Витебская' | 'Гомельская' | 'Гродненская' | 'Могилёвская' }

export const citiesBY: CitySeed[] = [
  { nameRu: 'Минск', nameBe: 'Мінск', region: 'Минская' },
  { nameRu: 'Брест', nameBe: 'Брэст', region: 'Брестская' },
  { nameRu: 'Витебск', nameBe: 'Віцебск', region: 'Витебская' },
  { nameRu: 'Гомель', nameBe: 'Гомель', region: 'Гомельская' },
  { nameRu: 'Гродно', nameBe: 'Гродна', region: 'Гродненская' },
  { nameRu: 'Могилёв', nameBe: 'Магілёў', region: 'Могилёвская' },
  // Минская область
  { nameRu: 'Борисов', nameBe: 'Барысаў', region: 'Минская' },
  { nameRu: 'Солигорск', nameBe: 'Салігорск', region: 'Минская' },
  { nameRu: 'Молодечно', nameBe: 'Маладзечна', region: 'Минская' },
  { nameRu: 'Жодино', nameBe: 'Жодзіна', region: 'Минская' },
  { nameRu: 'Слуцк', nameBe: 'Слуцк', region: 'Минская' },
  { nameRu: 'Вилейка', nameBe: 'Вілейка', region: 'Минская' },
  { nameRu: 'Дзержинск', nameBe: 'Дзяржынск', region: 'Минская' },
  { nameRu: 'Заславль', nameBe: 'Заслаўе', region: 'Минская' },
  { nameRu: 'Логойск', nameBe: 'Лагойск', region: 'Минская' },
  { nameRu: 'Несвиж', nameBe: 'Нясвіж', region: 'Минская' },
  { nameRu: 'Старые Дороги', nameBe: 'Старыя Дарогі', region: 'Минская' },
  { nameRu: 'Столбцы', nameBe: 'Стоўбцы', region: 'Минская' },
  { nameRu: 'Червень', nameBe: 'Чэрвень', region: 'Минская' },
  { nameRu: 'Любань', nameBe: 'Любань', region: 'Минская' },
  { nameRu: 'Марьина Горка', nameBe: 'Мар\'іна Горка', region: 'Минская' },
  { nameRu: 'Смолевичи', nameBe: 'Смалявічы', region: 'Минская' },
  { nameRu: 'Узда', nameBe: 'Узда', region: 'Минская' },
  { nameRu: 'Фаниполь', nameBe: 'Фаніпаль', region: 'Минская' },
  { nameRu: 'Клецк', nameBe: 'Клецк', region: 'Минская' },
  { nameRu: 'Копыль', nameBe: 'Капыль', region: 'Минская' },
  { nameRu: 'Крупки', nameBe: 'Крупкі', region: 'Минская' },
  // Брестская область
  { nameRu: 'Барановичи', nameBe: 'Баранавічы', region: 'Брестская' },
  { nameRu: 'Пинск', nameBe: 'Пінск', region: 'Брестская' },
  { nameRu: 'Кобрин', nameBe: 'Кобрын', region: 'Брестская' },
  { nameRu: 'Лунинец', nameBe: 'Лунінец', region: 'Брестская' },
  { nameRu: 'Жабинка', nameBe: 'Жабінка', region: 'Брестская' },
  { nameRu: 'Иваново', nameBe: 'Іванава', region: 'Брестская' },
  { nameRu: 'Ивацевичи', nameBe: 'Івацэвічы', region: 'Брестская' },
  { nameRu: 'Берёза', nameBe: 'Бяроза', region: 'Брестская' },
  { nameRu: 'Дрогичин', nameBe: 'Драгічын', region: 'Брестская' },
  { nameRu: 'Каменец', nameBe: 'Камянец', region: 'Брестская' },
  { nameRu: 'Ляховичи', nameBe: 'Ляхавічы', region: 'Брестская' },
  { nameRu: 'Малорита', nameBe: 'Маларыта', region: 'Брестская' },
  { nameRu: 'Микашевичи', nameBe: 'Мікашэвічы', region: 'Брестская' },
  { nameRu: 'Пружаны', nameBe: 'Пружаны', region: 'Брестская' },
  { nameRu: 'Столин', nameBe: 'Столін', region: 'Брестская' },
  { nameRu: 'Ганцевичи', nameBe: 'Ганцавічы', region: 'Брестская' },
  // Витебская область
  { nameRu: 'Орша', nameBe: 'Орша', region: 'Витебская' },
  { nameRu: 'Новополоцк', nameBe: 'Наваполацк', region: 'Витебская' },
  { nameRu: 'Полоцк', nameBe: 'Полацк', region: 'Витебская' },
  { nameRu: 'Глубокое', nameBe: 'Глыбокае', region: 'Витебская' },
  { nameRu: 'Поставы', nameBe: 'Паставы', region: 'Витебская' },
  { nameRu: 'Лепель', nameBe: 'Лепель', region: 'Витебская' },
  { nameRu: 'Браслав', nameBe: 'Браслаў', region: 'Витебская' },
  { nameRu: 'Бешенковичи', nameBe: 'Бешанковічы', region: 'Витебская' },
  { nameRu: 'Верхнедвинск', nameBe: 'Верхнядзвінск', region: 'Витебская' },
  { nameRu: 'Городок', nameBe: 'Гарадок', region: 'Витебская' },
  { nameRu: 'Докшицы', nameBe: 'Докшыцы', region: 'Витебская' },
  { nameRu: 'Дубровно', nameBe: 'Дуброўна', region: 'Витебская' },
  { nameRu: 'Миоры', nameBe: 'Міёры', region: 'Витебская' },
  { nameRu: 'Россоны', nameBe: 'Расоны', region: 'Витебская' },
  { nameRu: 'Сенно', nameBe: 'Сянно', region: 'Витебская' },
  { nameRu: 'Толочин', nameBe: 'Талачын', region: 'Витебская' },
  { nameRu: 'Чашники', nameBe: 'Чашнікі', region: 'Витебская' },
  { nameRu: 'Шарковщина', nameBe: 'Шаркаўшчына', region: 'Витебская' },
  { nameRu: 'Шумилино', nameBe: 'Шумілна', region: 'Витебская' },
  // Гомельская область
  { nameRu: 'Мозырь', nameBe: 'Мазыр', region: 'Гомельская' },
  { nameRu: 'Жлобин', nameBe: 'Жлобін', region: 'Гомельская' },
  { nameRu: 'Светлогорск', nameBe: 'Светлагорск', region: 'Гомельская' },
  { nameRu: 'Речица', nameBe: 'Рэчыца', region: 'Гомельская' },
  { nameRu: 'Калинковичи', nameBe: 'Калінкавічы', region: 'Гомельская' },
  { nameRu: 'Рогачёв', nameBe: 'Рагачоў', region: 'Гомельская' },
  { nameRu: 'Хойники', nameBe: 'Хойнікі', region: 'Гомельская' },
  { nameRu: 'Добруш', nameBe: 'Добруш', region: 'Гомельская' },
  { nameRu: 'Буда-Кошелёво', nameBe: 'Буда-Кашалёва', region: 'Гомельская' },
  { nameRu: 'Ветка', nameBe: 'Ветка', region: 'Гомельская' },
  { nameRu: 'Ельск', nameBe: 'Ельск', region: 'Гомельская' },
  { nameRu: 'Житковичи', nameBe: 'Жыткавічы', region: 'Гомельская' },
  { nameRu: 'Корма', nameBe: 'Корма', region: 'Гомельская' },
  { nameRu: 'Лельчицы', nameBe: 'Лельчыцы', region: 'Гомельская' },
  { nameRu: 'Лоев', nameBe: 'Лоеў', region: 'Гомельская' },
  { nameRu: 'Наровля', nameBe: 'Нароўля', region: 'Гомельская' },
  { nameRu: 'Октябрьский', nameBe: 'Кастрычніцкі', region: 'Гомельская' },
  { nameRu: 'Петриков', nameBe: 'Петрыкаў', region: 'Гомельская' },
  { nameRu: 'Чечерск', nameBe: 'Чачэрск', region: 'Гомельская' },
  // Гродненская область
  { nameRu: 'Лида', nameBe: 'Ліда', region: 'Гродненская' },
  { nameRu: 'Слоним', nameBe: 'Слонім', region: 'Гродненская' },
  { nameRu: 'Волковыск', nameBe: 'Ваўкавыск', region: 'Гродненская' },
  { nameRu: 'Сморгонь', nameBe: 'Смаргонь', region: 'Гродненская' },
  { nameRu: 'Новогрудок', nameBe: 'Навагрудак', region: 'Гродненская' },
  { nameRu: 'Островец', nameBe: 'Астравец', region: 'Гродненская' },
  { nameRu: 'Берёзовка', nameBe: 'Бярозаўка', region: 'Гродненская' },
  { nameRu: 'Скидель', nameBe: 'Скідзель', region: 'Гродненская' },
  { nameRu: 'Свислочь', nameBe: 'Свіслач', region: 'Гродненская' },
  { nameRu: 'Дятлово', nameBe: 'Дзятлава', region: 'Гродненская' },
  { nameRu: 'Зельва', nameBe: 'Зэльва', region: 'Гродненская' },
  { nameRu: 'Ивье', nameBe: 'Іўе', region: 'Гродненская' },
  { nameRu: 'Кореличи', nameBe: 'Карэлічы', region: 'Гродненская' },
  { nameRu: 'Мосты', nameBe: 'Масты', region: 'Гродненская' },
  { nameRu: 'Ошмяны', nameBe: 'Ашмяны', region: 'Гродненская' },
  { nameRu: 'Щучин', nameBe: 'Шчучын', region: 'Гродненская' },
  // Могилёвская область
  { nameRu: 'Бобруйск', nameBe: 'Бабруйск', region: 'Могилёвская' },
  { nameRu: 'Горки', nameBe: 'Горкі', region: 'Могилёвская' },
  { nameRu: 'Кричев', nameBe: 'Крычаў', region: 'Могилёвская' },
  { nameRu: 'Осиповичи', nameBe: 'Асіповічы', region: 'Могилёвская' },
  { nameRu: 'Костюковичи', nameBe: 'Касцюковічы', region: 'Могилёвская' },
  { nameRu: 'Шклов', nameBe: 'Шклоў', region: 'Могилёвская' },
  { nameRu: 'Климовичи', nameBe: 'Клімавічы', region: 'Могилёвская' },
  { nameRu: 'Белыничи', nameBe: 'Бялынічы', region: 'Могилёвская' },
  { nameRu: 'Быхов', nameBe: 'Быхаў', region: 'Могилёвская' },
  { nameRu: 'Глуск', nameBe: 'Глуск', region: 'Могилёвская' },
  { nameRu: 'Дрибин', nameBe: 'Дрыбін', region: 'Могилёвская' },
  { nameRu: 'Кировск', nameBe: 'Кіраўск', region: 'Могилёвская' },
  { nameRu: 'Краснополье', nameBe: 'Краснаполле', region: 'Могилёвская' },
  { nameRu: 'Круглое', nameBe: 'Круглае', region: 'Могилёвская' },
  { nameRu: 'Мстиславль', nameBe: 'Мсціслаў', region: 'Могилёвская' },
  { nameRu: 'Славгород', nameBe: 'Слаўгарад', region: 'Могилёвская' },
  { nameRu: 'Хотимск', nameBe: 'Хоцімск', region: 'Могилёвская' },
  { nameRu: 'Чаусы', nameBe: 'Чавусы', region: 'Могилёвская' },
  { nameRu: 'Чериков', nameBe: 'Чэрыкаў', region: 'Могилёвская' },
  { nameRu: 'Кличев', nameBe: 'Клічаў', region: 'Могилёвская' },
];
