/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    cities: City;
    media: Media;
    'audit-logs': AuditLog;
    'notification-preferences': NotificationPreference;
    'magic-link-tokens': MagicLinkToken;
    organizations: Organization;
    intakeFacilities: IntakeFacility;
    animals: Animal;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      organizations: 'organizations';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'notification-preferences': NotificationPreferencesSelect<false> | NotificationPreferencesSelect<true>;
    'magic-link-tokens': MagicLinkTokensSelect<false> | MagicLinkTokensSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    intakeFacilities: IntakeFacilitiesSelect<false> | IntakeFacilitiesSelect<true>;
    animals: AnimalsSelect<false> | AnimalsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  photoUrl?: string | null;
  phone?: string | null;
  telegramId?: string | null;
  telegramUsername?: string | null;
  role: 'guest' | 'citizen' | 'org_admin' | 'moderator' | 'superadmin';
  isBlocked?: boolean | null;
  lastSeenAt?: string | null;
  /**
   * Организации, где пользователь — админ
   */
  organizations?: {
    docs?: (number | Organization)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Подтверждено что 14+
   */
  ageConfirmed: boolean;
  /**
   * Согласие 99-З
   */
  consentPersonalData: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  /**
   * Генерируется из названия, если пусто
   */
  slug?: string | null;
  /**
   * УНП организации
   */
  unp?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  coverPhoto?: (number | null) | Media;
  city?: (number | null) | City;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  tgUrl?: string | null;
  viberUrl?: string | null;
  vkUrl?: string | null;
  instagramUrl?: string | null;
  websiteUrl?: string | null;
  donationBankDetails?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eripServiceCode?: string | null;
  isVerified?: boolean | null;
  isPublished?: boolean | null;
  /**
   * Пользователи-администраторы этой организации
   */
  admins?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  mediaKind: 'image' | 'video';
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  nameRu: string;
  nameBe: string;
  region: 'Минская' | 'Брестская' | 'Витебская' | 'Гомельская' | 'Гродненская' | 'Могилёвская';
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  actor?: (number | null) | User;
  action: string;
  targetType: string;
  targetId: string;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-preferences".
 */
export interface NotificationPreference {
  id: number;
  user: number | User;
  emailAdoptionInquiry?: boolean | null;
  emailModerationResult?: boolean | null;
  emailDonationReceipt?: boolean | null;
  /**
   * Города, по которым приходят алерты о срочных животных
   */
  emailUrgentInCities?: (number | City)[] | null;
  emailWeeklyDigest?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magic-link-tokens".
 */
export interface MagicLinkToken {
  id: number;
  tokenHash: string;
  user: number | User;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intakeFacilities".
 */
export interface IntakeFacility {
  id: number;
  name: string;
  slug?: string | null;
  city?: (number | null) | City;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Дней содержания по закону до возможной эвтаназии (хранится в БД, правит модератор)
   */
  legalHoldDays: number;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contactTgUrl?: string | null;
  viberUrl?: string | null;
  /**
   * Муниципальная служба (а не частный приют)
   */
  isMunicipal?: boolean | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals".
 */
export interface Animal {
  id: number;
  /**
   * Кличка (может быть пустой)
   */
  name?: string | null;
  petNumber?: number | null;
  slug?: string | null;
  species: 'dog' | 'cat' | 'other';
  sex?: ('male' | 'female' | 'unknown') | null;
  ageYears?: number | null;
  ageMonths?: number | null;
  size?: ('small' | 'medium' | 'large') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionPlain?: string | null;
  healthStatus?: ('healthy' | 'needs_treatment' | 'chronic_condition' | 'recovering' | 'unknown') | null;
  healthNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isSterilized?: boolean | null;
  isVaccinated?: boolean | null;
  /**
   * 15 цифр (опционально)
   */
  microchipId?: string | null;
  city?: (number | null) | City;
  ownerType: 'citizen' | 'organization';
  ownerUser?: (number | null) | User;
  organization?: (number | null) | Organization;
  status: 'pending_review' | 'published' | 'adopted' | 'archived';
  source?: ('web_form' | 'telegram_bot' | 'partner_feed' | 'admin') | null;
  lostOrFound?: ('none' | 'lost' | 'found') | null;
  /**
   * Фото (в MVP), видео — фаза 2
   */
  media?: (number | Media)[] | null;
  intakeFacility?: (number | null) | IntakeFacility;
  /**
   * Дата попадания в службу отлова
   */
  intakeDate?: string | null;
  /**
   * Дедлайн; авто из службы, можно override
   */
  legalDeadlineDate?: string | null;
  urgencyLevel?: ('normal' | 'high' | 'critical') | null;
  urgencyRank?: number | null;
  publishedAt?: string | null;
  adoptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'notification-preferences';
        value: number | NotificationPreference;
      } | null)
    | ({
        relationTo: 'magic-link-tokens';
        value: number | MagicLinkToken;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'intakeFacilities';
        value: number | IntakeFacility;
      } | null)
    | ({
        relationTo: 'animals';
        value: number | Animal;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  photoUrl?: T;
  phone?: T;
  telegramId?: T;
  telegramUsername?: T;
  role?: T;
  isBlocked?: T;
  lastSeenAt?: T;
  organizations?: T;
  ageConfirmed?: T;
  consentPersonalData?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  nameRu?: T;
  nameBe?: T;
  region?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  mediaKind?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-preferences_select".
 */
export interface NotificationPreferencesSelect<T extends boolean = true> {
  user?: T;
  emailAdoptionInquiry?: T;
  emailModerationResult?: T;
  emailDonationReceipt?: T;
  emailUrgentInCities?: T;
  emailWeeklyDigest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magic-link-tokens_select".
 */
export interface MagicLinkTokensSelect<T extends boolean = true> {
  tokenHash?: T;
  user?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  unp?: T;
  description?: T;
  logo?: T;
  coverPhoto?: T;
  city?: T;
  address?: T;
  phone?: T;
  email?: T;
  tgUrl?: T;
  viberUrl?: T;
  vkUrl?: T;
  instagramUrl?: T;
  websiteUrl?: T;
  donationBankDetails?: T;
  eripServiceCode?: T;
  isVerified?: T;
  isPublished?: T;
  admins?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intakeFacilities_select".
 */
export interface IntakeFacilitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  address?: T;
  phone?: T;
  email?: T;
  legalHoldDays?: T;
  description?: T;
  contactTgUrl?: T;
  viberUrl?: T;
  isMunicipal?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals_select".
 */
export interface AnimalsSelect<T extends boolean = true> {
  name?: T;
  petNumber?: T;
  slug?: T;
  species?: T;
  sex?: T;
  ageYears?: T;
  ageMonths?: T;
  size?: T;
  description?: T;
  descriptionPlain?: T;
  healthStatus?: T;
  healthNotes?: T;
  isSterilized?: T;
  isVaccinated?: T;
  microchipId?: T;
  city?: T;
  ownerType?: T;
  ownerUser?: T;
  organization?: T;
  status?: T;
  source?: T;
  lostOrFound?: T;
  media?: T;
  intakeFacility?: T;
  intakeDate?: T;
  legalDeadlineDate?: T;
  urgencyLevel?: T;
  urgencyRank?: T;
  publishedAt?: T;
  adoptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}